### PR TITLE
fix: allow inner loop traversals of SimpleCachingIteratorAggregate

### PR DESCRIPTION
**Pull request by rela589n**
This PR adds consecutive caching to `SimpleCachingIteratorAggregate` allowing to traverse the same iterator within the loop without affecting outer iteration.

See https://github.com/loophp/iterators/issues/49

### CODE REVIEW

**Comment by drupol** [comment]
Thanks for your pull request, I will review it carefully as soon as I have a bit of time.

**Comment by drupol** [comment]
I've updated a bit the PR, do you think we could do something to avoid the `if()` in the `foreach` ?

**Comment by drupol** [comment]
I found a case where this PR would not be valid, here it is:

<details>

```php
<?php

declare(strict_types=1);

namespace Issue49;

use loophp\iterators\SimpleCachingIteratorAggregate;

require __DIR__ . '/vendor/autoload.php';

function traverseAll(iterable $iter): array
{
    $items = [];

    foreach ($iter as $k => $v) {
        $items[$k] = $v;
    }

    return $items;
}

$input = static function () {
    yield 'a' => 1;
    yield 'a' => 2;
    yield 'a' => 3;
    yield 'a' => 4;
    yield 'a' => 5;
    yield 'a' => 6;
};

$iter = new SimpleCachingIteratorAggregate($input());

$outer = $inner = [];

foreach ($iter as $key => $item) {
    if ($key === 2) {
        $inner = traverseAll($iter);
    }

    $outer[$key] = $item;
}

print_r($inner);
print_r($outer);
```

</details>

The issue lies in the fact that we rely on the value of the key. Since there can be multiple same keys in an iterator, we need to find another way to achieve this if you want this PR to be merged.

**Comment by rela589n** [comment]
> I found a case where this PR would not be valid
> ...
> The issue lies in the fact that we rely on the value of the key. Since there can be multiple same keys in an iterator, we need to find another way to achieve this if you want this PR to be merged.

I'm not sure what is the expected behavior thereon.

I have just added `testSecondTraversalEliminatesDuplicatedKeys()` that passes regardless of current-PR changes and generally represents how `SimpleCachingIteratorAggregate` deals with duplicated keys on consecutive traversals.

These two statements accurately represent it:

```php
self::assertSame([
    ['a', 1],
    ['a', 2],
    ['a', 3],
], $firstIterationItems);

self::assertSame([
    ['a', 3],
], $secondIterationItems);
```

That being said, current logic of inner loop iterator traversal, looks expected to me:

```php
public function testInnerTraversalConsumesDuplicatedKeyValues(): void
{
    $input = static function (): Generator {
        yield 'a' => 1;
        yield 'a' => 2;
        yield 'a' => 3;
        yield 'b' => 4;
        yield 'b' => 5;
    };

    $iter = new SimpleCachingIteratorAggregate($input());

    $outerItems = $innerItems = [];

    foreach ($iter as $ko => $vo) {
        if ($vo === 2) {
            foreach ($iter as $ki => $vi) {
                $innerItems[] = [$ki, $vi];
            }
        }

        $outerItems[] = [$ko, $vo];
    }

    self::assertSame([
        ['a', 1],
        ['a', 2],
        ['b', 5],
    ], $outerItems);

    self::assertSame([
        ['a', 2],
        ['a', 3],
        ['b', 4],
        ['b', 5],
    ], $innerItems);
}
```

Please, let me know what you think on this matter.

Thank you!

**Comment by rela589n** [comment]
Hi there!

Just in case you don't like the idea behind suggested changes or the implementation, please let me know so that current PR may be closed.

Thank you

**Comment by drupol** [comment]
Hi !

I haven't had the time to review it yet... This weekend with the Fosdem it's not going to be possible. Planning to do it next week hopefully!

I'll keep you posted, no worries.

Cheers.

**Pull request closed without merging**
